// <auto-generated />
namespace PlusArgent_v1._0.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class plusargentv9 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(plusargentv9));
        
        string IMigrationMetadata.Id
        {
            get { return "201808221318381_plusargent-v9"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
